name: Build Outlook
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout new branch
        uses: actions/checkout@v3
      - name: "Run command"
        run: |
          sudo apt install npm -y
          sudo npm install nativefier -g
          nativefier --name Outlook --platform linux --arch x64 --width 1600 --height 900 --tray  --disable-old-build-warning-yesiknowitisinsecure --disable-dev-tools --single-instance https://outlook.office365.com/mail/
          cp icon/icon.png outlook-linux-x64/resources/app/
          mkdir -p Outlook/usr/share/applications/
          mkdir -p Outlook/DEBIAN
          cp debian/control Outlook/DEBIAN/control
          cp desktop/outlook.desktop Outlook/usr/share/applications/
          mv outlook-linux-x64 Outlook/usr/share/outlook
          dpkg-deb --build Outlook

      - name: "Create Release"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Outlook.deb"
          token: ${{ secrets.GITHUB_TOKEN}}
