name: Build Outlook
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout new branch
        uses: actions/checkout@v3
      - name: "Run command"
        run: |
          sudo apt install npm -y
          sudo npm install nativefier -g
          nativefier --name outlook --platform linux --arch x64 --width 1600 --height 900 --tray  --disable-old-build-warning-yesiknowitisinsecure --disable-dev-tools --single-instance https://outlook.office365.com/mail/
          cp icon/icon.png outlook-linux-x64/resources/app/
